### ISSUE TITLE
Add new blocks

### ISSUE THREAD

**Issue by Marl00** [AarnoldGad/fabric-mod-s6#1]
Hello !

I made some test with all the block and some of them can't be change with the debug stick.
Are you able to add this blocks on the mod please ?

- Mud brick stairs: minecraft:mud_brick_stairs
- Tuff brick stairs: minecraft:tuff_brick_stairs
- Polished tuff stairs: minecraft:polished_tuff_stairs
- Tuff stairs: minecraft:tuff_stairs
- Mud brick wall: minecraft:mud_brick_wall
- Tuff brick wall: minecraft:tuff_brick_wall
- Polished tuff wall: minecraft:polished_tuff_wall
- Tuff wall: minecraft:tuff_wall
- Copper trapdoor: minecraft:copper_trapdoor
- Exposed copper trapdoor: minecraft:exposed_copper_trapdoor
- Weathered copper trapdoor: minecraft:weathered_copper_trapdoor
- Oxidized copper trapdoor: minecraft:oxidized_copper_trapdoor
- Waxed copper trapdoor: minecraft:waxed_copper_trapdoor
- Waxed exposed copper trapdoor: minecraft:waxed_exposed_copper_trapdoor
- Waxed weathered copper trapdoor: minecraft:waxed_weathered_copper_trapdoor
- Waxed oxidized copper trapdoor: minecraft:waxed_oxidized_copper_trapdoor
- Copper door: minecraft:copper_door
- Exposed copper door: minecraft:exposed_copper_door
- Weathered copper door: minecraft:weathered_copper_door
- Oxidized copper door: minecraft:oxidized_copper_door
- Waxed copper door: minecraft:waxed_copper_door
- Waxed exposed copper door: minecraft:waxed_exposed_copper_door
- Waxed weathered copper door: minecraft:waxed_weathered_copper_door
- Waxed oxidized copper door: minecraft:waxed_oxidized_copper_door

The list may not be complete.
Be careful with logical names, there may be some errors.

Thanks ! TACK

**Comment by Marl00** [comment]
Are you able to add the blockstate for the candles please ? It's possible to turn On/Off the candle light

**Comment by gadjalin** [comment]
Hi Marl00,

Good catch! I apparently did not keep up very well with the latest MC updates...
I have now published a new release that should fix everything you mentioned (see https://github.com/AarnoldGad/fabric-mod-s6/releases/tag/0.0.4%2B1.21).

Additionally, I have added the possibility to modify some new block states:
- Furnaces (furnace, blast furnace and smoker) can be set to "lit". This is only visual and does not impact that actual ability of the furnace to cook. However, if you put something to cook in it, this will reset the state to either lit or unlit.
- Candles can also be set to lit, as well as candle cakes! (if you put candles on top of a cake)
- Copper bulbs can be set to lit, so that you can switch them on or off without a redstone signal.
- Signs, hanging signs and fence gates can be rotated.
- Hanging signs can also be set to "attached", which slightly modifies the look of the chain holding the sign.

Thank you again for your contribution! If you find anything else, please let us know.
